substitutions:
  name: "energy-meter"
  friendly_name: "Energy Meter Stream Server"

  # [Project]
  manufacturer: "espressif"
  project_name: "energy-meter-proxy"
  version: "2.0.4"
  serial_number: "41920942"

  # [UART]
  baudrate: "9600"
  data_bits: "8"
  parity: NONE
  stop_bits: "1"

  # [GPIOs]
  tx_pin: TX
  rx_pin: RX
  led_pin: GPIO25

  # [DLMS/COSEM]
  dlms_update_interval: 15s

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: ${manufacturer}.${project_name}
    version: ${version}
  on_boot:
    priority: 600
    then:
      - component.update: pending_errors
      - if:
          condition:
            - binary_sensor.is_on: optical_port
          then:
            - light.turn_on: connection_status
          else:
            - light.turn_off: connection_status
      

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    advanced:
      minimum_chip_revision: "3.1"
      sram1_as_iram: true

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret strawberry__api_key
  actions:
    - action: reset_pending_errors
      then:
        - globals.set:
            id: error_number
            value: "0"

mdns:
            
globals:
  id: error_number
  type: int
  restore_value: True
  initial_value: "0"

ota:
  - platform: esphome
    encryption:

wifi:
  ssid: !secret wifi_iot2_ssid
  password: !secret wifi_iot2_password
  ap:
    ssid: "${name} Fallback Hotspot"
    password: !secret strawberry__fallback_password

  manual_ip:
    static_ip: !secret strawberry__ip
    gateway: 192.168.2.1
    subnet: 255.255.255.0

captive_portal:

external_components:
  - source: github://denpaforks/esphome-dlms-cosem
    components: [ dlms_cosem ]

interval:
  - interval: 24h
    startup_delay: 24h
    then:
      - button.press: restart_node
    
uart:
  baud_rate: ${baudrate}
  data_bits: ${data_bits}
  parity: ${parity}
  stop_bits: ${stop_bits}
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  rx_buffer_size: 2048

dlms_cosem:
  client_address: 32
  server_address:
    logical_device: 1
    physical_device: 42
    address_length: 2
  delay_between_requests: 25ms
  auth: true
  password: !secret strawberry__meter_password
  update_interval: ${dlms_update_interval}

button:
  - platform: restart
    id: restart_node
    name: "Restart node"

sensor:
  - platform: wifi_signal
    name: "WLAN RSSI"

  - platform: dlms_cosem
    name: "Current L1"
    obis_code: 1.0.31.7.0.255
    unit_of_measurement: A
    accuracy_decimals: 3
    device_class: current
    state_class: measurement

  - platform: dlms_cosem
    name: "Current L2"
    obis_code: 1.0.51.7.0.255
    unit_of_measurement: A
    accuracy_decimals: 3
    device_class: current
    state_class: measurement

  - platform: dlms_cosem
    name: "Current L3"
    obis_code: 1.0.71.7.0.255
    unit_of_measurement: A
    accuracy_decimals: 3
    device_class: current
    state_class: measurement

  - platform: dlms_cosem
    name: "Voltage L1"
    obis_code: 1.0.32.7.0.255
    unit_of_measurement: V
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement

  - platform: dlms_cosem
    name: "Voltage L2"
    obis_code: 1.0.52.7.0.255
    unit_of_measurement: V
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement

  - platform: dlms_cosem
    name: "Voltage L3"
    obis_code: 1.0.72.7.0.255
    unit_of_measurement: V
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement

  - platform: dlms_cosem
    name: "Active power total"
    obis_code: 1.0.1.7.0.255
    unit_of_measurement: W
    accuracy_decimals: 1
    device_class: power
    state_class: measurement

  - platform: dlms_cosem
    name: "Active power L1"
    obis_code: 1.0.21.7.0.255
    unit_of_measurement: W
    accuracy_decimals: 1
    device_class: power
    state_class: measurement

  - platform: dlms_cosem
    name: "Active power L2"
    obis_code: 1.0.41.7.0.255
    unit_of_measurement: W
    accuracy_decimals: 1
    device_class: power
    state_class: measurement

  - platform: dlms_cosem
    name: "Active power L3"
    obis_code: 1.0.61.7.0.255
    unit_of_measurement: W
    accuracy_decimals: 1
    device_class: power
    state_class: measurement

  - platform: dlms_cosem
    name: "Apparent power total"
    obis_code: 1.0.9.7.0.255
    unit_of_measurement: VA
    accuracy_decimals: 1
    device_class: apparent_power
    state_class: measurement

  - platform: dlms_cosem
    name: "Apparent power L1"
    obis_code: 1.0.29.7.0.255
    unit_of_measurement: VA
    accuracy_decimals: 1
    device_class: apparent_power
    state_class: measurement

  - platform: dlms_cosem
    name: "Apparent power L2"
    obis_code: 1.0.49.7.0.255
    unit_of_measurement: VA
    accuracy_decimals: 1
    device_class: apparent_power
    state_class: measurement

  - platform: dlms_cosem
    name: "Apparent power L3"
    obis_code: 1.0.69.7.0.255
    unit_of_measurement: VA
    accuracy_decimals: 1
    device_class: apparent_power
    state_class: measurement

  - platform: dlms_cosem
    name: "Power factor total"
    obis_code: 1.0.13.7.0.255
    accuracy_decimals: 3
    device_class: power_factor
    state_class: measurement
    filters:
      - or:
        - throttle: 60s
        - delta: 0.05

  - platform: dlms_cosem
    name: "Power factor L1"
    obis_code: 1.0.33.7.0.255
    accuracy_decimals: 3
    device_class: power_factor
    state_class: measurement
    filters:
      - or:
        - throttle: 60s
        - delta: 0.05

  - platform: dlms_cosem
    name: "Power factor L2"
    obis_code: 1.0.53.7.0.255
    accuracy_decimals: 3
    device_class: power_factor
    state_class: measurement
    filters:
      - or:
        - throttle: 60s
        - delta: 0.05

  - platform: dlms_cosem
    name: "Power factor L3"
    obis_code: 1.0.73.7.0.255
    accuracy_decimals: 3
    device_class: power_factor
    state_class: measurement
    filters:
      - or:
        - throttle: 60s
        - delta: 0.05

  - platform: dlms_cosem
    name: "Active energy total"
    obis_code: 1.0.1.8.0.255
    unit_of_measurement: kWh
    accuracy_decimals: 2
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001

  - platform: dlms_cosem
    id: energy_tariff1
    name: "Active energy tariff 1"
    obis_code: 1.0.1.8.1.255
    unit_of_measurement: kWh
    accuracy_decimals: 2
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001

  - platform: dlms_cosem
    id: energy_tariff2
    name: "Active energy tariff 2"
    obis_code: 1.0.1.8.2.255
    unit_of_measurement: kWh
    accuracy_decimals: 2
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001

  - platform: dlms_cosem
    name: "Frequency"
    obis_code: 1.0.14.7.0.255
    unit_of_measurement: Hz
    accuracy_decimals: 2
    device_class: frequency
    state_class: measurement
    filters:
      - or:
        - throttle: 60s
        - delta: 0.1

  - platform: dlms_cosem
    name: "Internal temperature"
    obis_code: 0.0.96.9.0.255
    unit_of_measurement: C
    accuracy_decimals: 0
    device_class: temperature
    state_class: measurement
    entity_category: diagnostic

  - platform: dlms_cosem
    id: current_tariff
    obis_code: 0.0.96.14.0.255
    obis_class: 1
    accuracy_decimals: 0
    entity_category: diagnostic
    on_value:
      then:
        - component.update: human_readable_tariff

  - platform: dlms_cosem
    id: self_test
    obis_code: 0.0.97.97.0.255
    obis_class: 1
    accuracy_decimals: 0
    entity_category: diagnostic
    on_value:
      then:
        - if:
            condition:
              - and:
                - lambda: "return x != 0.0;"
                - lambda: "return id(error_number) != (int)x;"
            then:
              - globals.set:
                  id: error_number
                  value: !lambda "return (id(error_number) | (int)x);"
              - component.update: pending_errors

  - platform: template
    name: "Night tariff utilization"
    icon: "mdi:lightbulb-night"
    lambda: |-
      if (isnan(id(energy_tariff1).state) || isnan(id(energy_tariff2).state) || id(energy_tariff1).state == 0.0) {
        return {};
      } else {
        return (id(energy_tariff2).state / id(energy_tariff1).state) * 100.0;
      }
    unit_of_measurement: "%"
    accuracy_decimals: 1
    state_class: measurement


text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    mac_address:
      name: "MAC Address"

  - platform: template
    name: "Serial number"
    icon: "mdi:barcode"
    lambda: "return \"${serial_number}\";"
    entity_category: diagnostic

  - platform: dlms_cosem
    name: "Date and time"
    icon: "mdi:calendar"
    obis_code: 0.0.1.0.0.255
    entity_category: diagnostic
    obis_class: 8

  - platform: dlms_cosem
    name: "Clock synced at"
    icon: "mdi:clock-check"
    device_class: timestamp
    obis_code: 0.0.96.2.12.255
    entity_category: diagnostic
    obis_class: 1
    cp1251: False
    data_type: datetime
    filters:
      - lambda: |-
          return x.substr(0, 10) + "T" + x.substr(11, 8) + x.substr(23);

  - platform: template
    id: pending_errors
    name: "Pending errors"
    icon: "mdi:alert-circle"
    update_interval: never
    lambda: |-
      if(id(error_number) == -1) {
        return {};
      }
      if(id(error_number) == 0) {
        return "None";
      }
      std::string error_string = "";
      int error_length = sizeof(error_number);
      for (int index = 0; index < (error_length - 1); ++index) {
        if (id(error_number) & (1 << index)) {
          if (!error_string.empty()) {
            error_string += ", ";
          }
          char buf[8];
          snprintf(buf, sizeof(buf), "E-%02d", index + 1);
          error_string += buf;
        }
      }
      return error_string;
    entity_category: diagnostic

#  - platform: dlms_cosem
#    name: "Serial number"
#    icon: "mdi:barcode"
#    obis_code: 0.0.96.1.0.255
#    entity_category: diagnostic

  - platform: template
    id: human_readable_tariff
    name: "Current Tariff"
    icon: "mdi:meter-electric"
    lambda: |-
      float tariff = id(current_tariff).state;
      if (tariff == 1.0) return {"Day"};
      if (tariff == 2.0) return {"Night"};
      return {};
    update_interval: never

binary_sensor:
  - platform: status
    name: "Node status"

  - platform: template
    name: "Self-diagnostics"
    device_class: problem
    entity_category: diagnostic
    lambda: |-
      if (id(self_test).state > 0.0) {
        return true;
      } else {
        return false;
      }

  - platform: dlms_cosem
    connection:
      id: optical_port
      name: "Optical port"
      icon: "mdi:swap-horizontal-circle"
      on_press:
        light.turn_on: connection_status
      on_release:
        light.turn_off: connection_status

light:
  - platform: status_led
    id: connection_status
    pin: ${led_pin}
